name: GridSelector
version: ${version}
api-version: 1.13
author: Hadde
main: de.eldoria.gridselector.GridSelector
depend:
  - SchematicBrushReborn
softdepend:
  - PlotSquared
  - WorldGuard
commands:
  schematicbrushgrid:
    aliases: sbrg
    permission: gridselector.use
